source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_dependencies', '~> 0.23'
gem 'rake_terraform', '~> 0.31'
gem 'ruby-terraform', '~> 0.46'
gem 'confidante', '~> 0.12.0.pre.1'
gem 'lino', '~> 1.1'
gem 'rspec', '~> 3.9'
gem 'awspec', '~> 1.18'
gem 'git', '~> 1.5'
gem 'semantic', '~> 1.6'
