source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_dependencies', '~> 2.9'
gem 'rake_terraform', '~> 1.19'
gem 'rake_circle_ci', '~> 0.9'
gem 'rake_github', '~> 0.7'
gem 'rake_ssh', '~> 0.6'
gem 'rake_gpg', '~> 0.16'
gem 'confidante', '~> 0.27'
gem 'rspec', '~> 3.9'
gem 'awspec', '~> 1.22'
gem 'git', '~> 1.7'
gem 'semantic', '~> 1.6'
