#!/bin/sh
AUTHORS="${AUTHORS:-@tobyclemson}"
STORY_NUMBER="${STORY_NUMBER:-1}"

case "$2,$3" in
  merge,)
    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;

 ,|template,)
    sed -i.bak -e "1s/^/[$STORY_NUMBER] Authors: $AUTHORS/" "$1" ;;
  *) ;;
esac
